### ISSUE TITLE
REDCap Testing (Brainstorming)

### ISSUE THREAD

**Issue by thomasnwilson** [OuhscBbmc/RedcapGovernanceDocs#21]
@wibeasley @bard1536 

With regards to upgrading the instances of REDCap:

What do we want to test?
How do we want to test them?

Ideas that David and I discussed:

Creating bogus projects in the devbox.  After REDCap has been upgraded, test these bogus projects to ensure that all features are working correctly.

Have a standard "new" project to create in the new version on the devbox.

Testing the superuser features (deleting a project etc)

What are your thoughts?

**Comment by wibeasley** [comment]
Although the understanding isn't easily formalized in writing, we've developed a basic approach for these scenarios.

As long as plug-ins aren't used, the projects aren't migrated to the dev box for testing, unless a new REDCap feature has been released that we suspect might break an existing project's functionality.
