### ISSUE TITLE
REDCap address change and aliases

### ISSUE THREAD

**Issue by DavidBard** [OuhscBbmc/RedcapGovernanceDocs#7]
@thomasnwilson 

I'd like for our REDCap address name to change from ~miechvprojects.~
to ~redcapbbmc.~

Also, please check to see if we can use aliases for individual projects.  Be sure to ask what happens when an alias is appended with a private survey tag.  

Thanks.

**Comment by wibeasley** [comment]
The url was changed a while ago.
